### ISSUE TITLE
Decon Shower

### ISSUE THREAD

**Issue by Grewsome2018** [diwako/diwako_cbrn#1]
Hiya mate,

Only thing I've found is the decon showers don't provide the hints and the 2 second timeout doesn't "fix" the contamination. It creates the puddle so at least part of the code is running. I'm not sure if you've had any other reports of issues or anything like this in the past? I can see from the forums there's been hardly any issues but any guidance would be welcomed. Other than that it's a great script!

Cheers,
Grew

**Comment by diwako** [comment]
Hey, The contamination damage you receive will not be healed by showering. The showers only function is to stop auto contamination once you reach 50% of the maximum on CBRN damage you can take.

E.g. Max CBRN damage is 100. You run around without proper CBRN protection until you get to 50% damage. You get a pop up that you are really badly contaminated and should search for a decon shower. This means you will gain passively more CBRN damage until your wash that stuff off. Go to a shower , activate it and stand in it for some seconds, THEN the new pop up should appear saying the auto contamination has stopped.
As said before showers are not meant to heal you, just to stop you form gaining more CBRN damage through the passive damage system,

**Comment by Grewsome2018** [comment]
Hey mate, thanks for the prompt reply - apologies for it taking me so long to get back to ya. Thanks for explaining that, it makes a lot more sense hearing it now. To confirm, there is no function called or current methodology to "heal" the decon damage? Reason I ask is that we have a medical trigger that calls the ACE medical function to fully heal the lads that enter the trigger but the CBRN damage doesn't seem to get affected by it.

Cheers

**Comment by diwako** [comment]
While this script does not "heal" the damage due to it taking a long time, way longer than the mission is running really. You however can reset or set the damage yourself in your own scripts.

```sqf
player setVariable ["cbrn_damage", nil];
```
`nil` or `0` to reset the damage to `0`. Put in any other number between `0` and your max damage to set damage, anything above should kill.

Two more values you can set. They are related to the auto damage.
```sqf
player setVariable ["cbrn_autoDamage", nil];
player setVariable ["cbrn_stoppedAutoDamage", nil];
```

This resets the auto damage ticker to be primed again once you hit the half way point. You can set the `cbrn_stoppedAutoDamage` to `true` to never have the auto damage kick in to begin with.

**Comment by Grewsome2018** [comment]
Hey bro,

Thanks very much for taking the time to pass those variables on. Big help. 

Cheers,
Grew
